name: Linux workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt update -y && sudo apt install meson build-essential libmagick++-dev -y
    - name: Set up build directory
      run: meson setup builddir
    - name: Build
      run: meson compile -C builddir
    - name: Upload built executable
      uses: actions/upload-artifact@v3.1.3
      with:
        name: linux
        path: builddir/b16converter
  test:
    name: Test on Linux
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt update -y && sudo apt install meson build-essential libmagick++-dev -y
    - name: Download executable
      uses: actions/download-artifact@v2.1.1
      with:
        name: linux
        path: b16convert
    - name: Set up build directory
      run: meson setup builddir
    - name: Run test script
      run: ./test.sh -p b16convert
    - name: Upload test artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: test-files
        path: testout
