name: Test on Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt update -y && sudo apt install meson build-essential libmagick++-dev -y
    - name: Set up build directory
      run: meson setup builddir
    - name: Run test script
      run: ./test.sh
    - name: Upload test artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: test-files
        path: testout
