name: Build for Windows using MSys2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys@v2
      with:
        msystem: UCRT64
        update: true
        install: git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-imagemagick mingw-w64-ucrt-x86_64-meson
    - name: Set up build directory
      run: meson setup builddir
    - name: Build
      run: meson compile -C builddir
    - name: Upload built executable
      uses: actions/upload-artifact@v3.1.3
      with:
        name: windows
        path: builddir/b16converter.exe
